### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Exyztence** [Bunny5578/qb-wheelchair#4]
Hi, sadly the QB wheelchair ain't working for me. I've added an item and added an image but using a wheelchair doesn't do anything. It only prints your message to the console

[script:qb-wheelchair] usado

but nothing spawns etc.
Any help please? :)

**Comment by Exyztence** [comment]
Fixed, I've downloaded iak_wheelchair model and uploaded it to cars folder

**Comment by Bunny5578** [comment]
Hello sorry for not replying in time I had no clue someone had a issue

**Comment by Bunny5578** [comment]
Hello sorry for not replying in time I had no clue someone had a issue
